config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
include PgSearch::Model

pg_search_scope :search_full_text,
against: {
            username: 'A'
        }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @pagy, @tweets = pagy(Tweet.all)
    if params[:query_text].present?
      @tweets = @tweets.search_full_text(params[:query_text])
      end
  end
  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet fue creada con éxito.." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet fue actualizada con éxito." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pruebafinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Descripción, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :usuario, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit "Editar" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">

    <div class="card">
      <div class="card-header"> 
      <h6>Usuario: <%= tweet.username %><h6> 
      
      </div>
      <div class="card-body">
        <p class="card-title"">Descripción: 
        <%= tweet.description %>  <a>Id: <%= tweet.id %>  <a> 
        </p>       
      </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editando un tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Mostrar tweet", @tweet %> |
  <%= link_to "Regresar a tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<h1>Tweets Index</h1><br>
<%= link_to "Crear un nuevo tweet" , new_tweet_path %>
<br>
<h5>Buscar Tweet </h5>
<p style="color: red">
  <%= notice %>
</p>

<%= form_with url: tweets_path, method: :get do |form|%>
<%= form.text_field :query_text, placeholder: t('Buscador de usuarios'), value: params[:query_text]%>
<%end%><br><br>
  <div id="tweets">
    <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
    <%= link_to "Mostrar" , tweet %>
    </p>
    <% end %>
  </div>
<%=raw pagy_nav(@pagy)%>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Regresar a tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<h1>Mostrar</h1>
<p style="color: red"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Editar tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Regresar a tweets", tweets_path %>

  <%= button_to "ELIMINAR", @tweet, method: :delete %>
</div>